const express = require("express");
const bodyParser = require("body-parser");
//const cookieParser = require('cookie-parser');
const bcrypt = require('bcryptjs');
const PORT = 8080;
const app = express();
const cookieSession = require("cookie-session");

app.use(bodyParser.urlencoded({ extended: true }));
//app.use(cookieParser());
app.use(cookieSession({
  name: "session",
  keys: ["super secret key"],
}));


// set the view engine to ejs
app.set('view engine', 'ejs');

const urlDatabase = {
  b6UTxQ: {
    longURL: "https://www.tsn.ca",
    userID: "aJ48lW",
  },
  i3BoGr: {
    longURL: "https://www.google.ca",
    userID: "aJ48lW",
  },
};

const users = {
  "userRandomID": {
    id: "userRandomID",
    email: "user@example.com",
    password: "purple-monkey-dinosaur"
  },
  "user2RandomID": {
    id: "user2RandomID",
    email: "user2@example.com",
    password: "dishwasher-funk"
  }
};

//POST request for user to register input information
app.post("/register", (req, res) => {
  const email = req.body.email;
  const password = req.body.password;
  const hashedPassword = bcrypt.hashSync(password);
  //If the e-mail or password are empty strings, send back a response with the 400 status code.
  if (!email || !password) {
    return res.status(400).send("Please enter valid inputs!");
  }
  
  //If someone tries to register with an email that is already in the users object,
  if (getUserByEmail(email, users)) {
    return res.status(403).send("SORRY: This email has already been used");
  }
  
  const id = generateRandomString(4);
  
  const user = {
    id: id,
    email: email,
    password: hashedPassword,
  };
  users[id] = user;
  
  res.redirect("/login");
});
  
  
const getUserByEmail = function(email, database) {
  
  for (const userId in database) {
    const user = database[userId];
    if (user.email === email) {
      return user; // user found return user object
    }
  }
  return null; //user not found
};

    
// POST req for user login
app.post("/login", (req, res) => {
  const email = req.body.email;
  const password = req.body.password;
  const user = getUserByEmail(email, users);
  
  if (!user) {
    return res.status(403).send(`SORRY: Could not find a user with the email ${email}`);
  }
  if (!bcrypt.compareSync(password, user.password)) {
    return res.status(401).send("SORRY: This login information is invalid");
  }
  req.session.userId = user.id; // set cookie
  res.redirect("/urls");
});

//POST request for Logout
app.post("/logout", (req, res) => {
  
  req.session = null;// clear cookie
  res.redirect("/login");
});

//POST route that removes a URL by accessing shortURL key
app.post("/urls/:shortURL/delete", (req, res) => {
  const shortURL = req.params.shortURL;//access shortURL with req.params.shortURL
  const userID = req.session.userId;
  if (!userID || urlDatabase[shortURL].userID !== userID) {
    return res.status(401).send("SORRY: You must be logged in to delete url!");
  }
  
  delete urlDatabase[shortURL];//delete from data base by using delete and acessing shortURL key with bracket notation
  res.redirect("/urls");
});

  

// POST request from client to edit URLs
app.post("/urls/:id", (req, res) => {
  //rq.params.id is the data that comes from the input form. It's accessed and assigned to the newShortURL variable
  const newShortUrl = req.params.id;
  const userID = req.session.userId;
  if (!userID || urlDatabase[newShortUrl].userID !== userID) {
    return res.status(401).send("SORRY: You must be logged in to edit a url!");
  }
  
  //Then the newShortURL is used to update the req.body.longURL which is the edited URL from the client. All is updated on the database
  urlDatabase[newShortUrl].longURL = req.body.longURL;
  
    res.redirect(`/urls/${newShortUrl}`);
  
});
  

//Post to urls page where list of urls with their shortURL keys is looped over and displayed
app.post("/urls", (req, res) => {
  
  const userID = req.session.userId;
  
  if (!userID) {
    return res.status(401).send("SORRY: You must be logged in to add new url!");
  }
  const longURL = req.body.longURL;
  let newShortUrl = generateRandomString(6); // var  newShortUrl is given the value generated by the randomString func
  urlDatabase[newShortUrl] = { userID , longURL }; //urlDatabase is updated by assigning the value of req.body.longURL (the long url path)to the newShortUrl key
  
  res.redirect(`/urls/${newShortUrl}`); // Redirects to /urls/with the new short url value displayed
});

const characters =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

const generateRandomString = function(length) {
  let result = "";
  const charactersLength = characters.length;

  //For loop is used to loop through the number passed into the generateRandomString() function
  //During each iteration, a random character is generated.
  for (let i = 0; i < length; i++) {
    //Math.random() method is used to generate random characters from the specified characters var
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }

  return result;
};

//Get request for register file
app.get("/register", (req, res) => {
  const loggedInUser = req.session.userId;
  const templateVars = { user: users[loggedInUser] };
  res.render("register", templateVars);
});

//Get request for login file
app.get("/login", (req, res) => {
  const loggedInUser = req.session.userId;
  const templateVars = { user: users[loggedInUser] };
  res.render("login", templateVars);
});

//Loops through database and finds shortURL objects that match the logged in user
const urlsForUserId = function(database, userId) {
  const loggedInUserUrls = {};

  for (let shortURL in database) {
    if (database[shortURL].userID === userId) {
      loggedInUserUrls[shortURL] = database[shortURL];
    }
  }
  return loggedInUserUrls;
};


//Get page /urls where list of urls is looped over and displayed
app.get("/urls", (req, res) => {
  const loggedInUser = req.session.userId;
  if (!loggedInUser) {
    res.status(401).send("Please login to access Tinyapp.");
  }

  const urlsForUser = urlsForUserId(urlDatabase, loggedInUser);
  const templateVars = { urls: urlsForUser, user: users[loggedInUser] };
  
  res.render("urls_index", templateVars);
});

app.get("/urls/new", (req, res) => {

  const loggedInUser = req.session.userId;
  if (!loggedInUser) {
    res.redirect("/login");
  }
  
  const templateVars = { user: users[loggedInUser] };
  res.render("urls_new", templateVars);
});

app.get("/urls/:shortURL", (req, res) => {
  const shortURL = req.params.shortURL;
  const longURL = urlDatabase[req.params.shortURL].longURL;
  const loggedInUser = req.session.userId;
  if (!loggedInUser || urlDatabase[shortURL].userID !== loggedInUser) {
    return res.status(401).send("SORRY: You do no have permission to access this page!");
  }
  const templateVars = { shortURL, longURL, user: users[loggedInUser] };
  res.render("urls_show", templateVars);
});
  

//Get new route for shortURL requests. Where it redirects to the corresponding longURL
app.get("/u/:shortURL", (req, res) => {
  
  const longURL =  urlDatabase[req.params.shortURL].longURL;
  if (!longURL) {
    res.status(401).send("Sorry: Incorrect URL");
  }
  res.redirect(longURL);
});
  

app.listen(PORT, () => {
  console.log(`Example app listening on port ${PORT}!`);
});


